import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  contrastRatio,
  resolve as resolveContrast,
  emitCustomProps,
  header,
  type ContrastDecision,
  type FailingPair,
} from '@veil-ncss/tokens-shared';
import { palette, aliasMap, pairings } from './config/palette.js';
import { overrides } from './config/color-overrides.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST = join(__dirname, 'dist');
const REPO_ROOT = resolvePath(__dirname, '..', '..');
const DOCS = join(REPO_ROOT, 'docs');

async function ensureDirs() {
  await mkdir(DIST, { recursive: true });
  await mkdir(DOCS, { recursive: true });
}

interface ResolvedPairing {
  role: string;
  fg: string;
  bg: string;
  ratio: number;
  large: boolean;
}

function runContrastResolution(): {
  decisions: ContrastDecision[];
  finalPairings: ResolvedPairing[];
  resolvedPaletteOverrides: Record<string, string>;
} {
  const decisions: ContrastDecision[] = [];
  const finalPairings: ResolvedPairing[] = [];
  const paletteRewrite: Record<string, string> = {};

  const lockedLower = {
    lockedBackgrounds: overrides.lockedBackgrounds.map((c) => c.toLowerCase()),
    lockedForegrounds: overrides.lockedForegrounds.map((c) => c.toLowerCase()),
  };

  for (const p of pairings) {
    const failing: FailingPair = {
      pairKey: `${p.role}`,
      fg: p.fg,
      bg: p.bg,
      role: p.role,
      large: p.large ?? false,
    };
    const decision = resolveContrast(failing, lockedLower);
    decisions.push(decision);

    if (decision.strategy === 'manual-override') {
      console.error(
        `[tokens-veil] FAIL: ${p.role} (${p.fg} on ${p.bg}) — ${decision.rationale}`,
      );
      finalPairings.push({
        role: p.role,
        fg: decision.fgAdjusted,
        bg: decision.bgAdjusted,
        ratio: decision.ratioAdjusted,
        large: decision.large,
      });
      continue;
    }

    finalPairings.push({
      role: p.role,
      fg: decision.fgAdjusted,
      bg: decision.bgAdjusted,
      ratio: decision.ratioAdjusted,
      large: decision.large,
    });

    if (decision.strategy === 'adjust-fg' && decision.fgAdjusted !== decision.fgOriginal) {
      paletteRewrite[decision.fgOriginal.toLowerCase()] = decision.fgAdjusted;
    }
    if (decision.strategy === 'adjust-bg' && decision.bgAdjusted !== decision.bgOriginal) {
      paletteRewrite[decision.bgOriginal.toLowerCase()] = decision.bgAdjusted;
    }
  }

  return { decisions, finalPairings, resolvedPaletteOverrides: paletteRewrite };
}

function rewritePalette(rewrite: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [name, value] of Object.entries(palette)) {
    const lower = value.toLowerCase();
    out[name] = rewrite[lower] ?? value;
  }
  return out;
}

function colorDecisionsMd(decisions: ContrastDecision[]): string {
  const lines: string[] = [];
  lines.push('# Veil — Color Decisions');
  lines.push('');
  lines.push('Generated by `packages/tokens-veil/build.ts`. Review with client before sign-off.');
  lines.push('');
  lines.push('| Role | Original | Adjusted | Ratio (was → now) | Strategy | Rationale |');
  lines.push('|---|---|---|---|---|---|');
  for (const d of decisions) {
    const orig = `\`${d.fgOriginal}\` on \`${d.bgOriginal}\``;
    const adj = `\`${d.fgAdjusted}\` on \`${d.bgAdjusted}\``;
    const ratios = `${d.ratioOriginal.toFixed(2)} → ${d.ratioAdjusted.toFixed(2)}`;
    lines.push(`| ${d.role}${d.large ? ' (large)' : ''} | ${orig} | ${adj} | ${ratios} | ${d.strategy} | ${d.rationale} |`);
  }
  lines.push('');
  return lines.join('\n');
}

async function main() {
  await ensureDirs();

  const { decisions, finalPairings, resolvedPaletteOverrides } = runContrastResolution();
  const adjustedPalette = rewritePalette(resolvedPaletteOverrides);

  const manualOverrides = decisions.filter((d) => d.strategy === 'manual-override');
  if (manualOverrides.length > 0) {
    console.error(
      `[tokens-veil] ${manualOverrides.length} pairing(s) require manual review. See docs/color-decisions.md.`,
    );
  }

  const paletteCss = emitCustomProps(
    ':root, :root[data-brand="veil"]',
    adjustedPalette,
    'Veil palette (raw — components must consume via aliases)',
  );
  const aliasCss = emitCustomProps(
    ':root, :root[data-brand="veil"]',
    aliasMap,
    'Veil alias overrides',
  );

  const indexCss = [
    header('@veil-ncss/tokens-veil — Veil brand layer'),
    paletteCss,
    '',
    aliasCss,
  ].join('\n');

  await writeFile(join(DIST, 'index.css'), indexCss + '\n', 'utf8');

  const model = {
    brand: 'veil' as const,
    palette: adjustedPalette,
    aliasOverrides: aliasMap,
    pairings: finalPairings,
    decisions,
  };
  await writeFile(join(DIST, 'model.json'), JSON.stringify(model, null, 2) + '\n', 'utf8');

  await writeFile(join(DOCS, 'color-decisions.md'), colorDecisionsMd(decisions), 'utf8');

  for (const p of finalPairings) {
    const checkedRatio = contrastRatio(p.fg, p.bg);
    const target = p.large ? 3 : 4.5;
    if (checkedRatio < target) {
      console.error(
        `[tokens-veil] BUILD FAILURE: pairing "${p.role}" still under AA (${checkedRatio.toFixed(2)} < ${target}).`,
      );
      process.exit(2);
    }
  }

  console.log(
    `[tokens-veil] wrote ${Object.keys(adjustedPalette).length} palette tokens, ${Object.keys(aliasMap).length} alias overrides, ${finalPairings.length} verified pairings.`,
  );
}

main().catch((err) => {
  console.error('[tokens-veil] build failed:', err);
  process.exit(1);
});
